/** \file
 *  This C header file was generated by $ANTLR version 3.2 Sep 23, 2009 12:02:23
 *
 *     -  From the grammar source file : ProtoJS.g
 *     -                            On : 2011-09-06 17:46:47
 *     -                 for the lexer : ProtoJSLexerLexer *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer ProtoJSLexer has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 * 
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pProtoJSLexer, which is returned from a call to ProtoJSLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 * * The methods in pProtoJSLexer are  as follows:
 *
 *  -  void      pProtoJSLexer->PACKAGELITERAL(pProtoJSLexer)
 *  -  void      pProtoJSLexer->IMPORTLITERAL(pProtoJSLexer)
 *  -  void      pProtoJSLexer->DOT(pProtoJSLexer)
 *  -  void      pProtoJSLexer->SERVICE(pProtoJSLexer)
 *  -  void      pProtoJSLexer->RPC(pProtoJSLexer)
 *  -  void      pProtoJSLexer->RETURNS(pProtoJSLexer)
 *  -  void      pProtoJSLexer->MESSAGE(pProtoJSLexer)
 *  -  void      pProtoJSLexer->EXTEND(pProtoJSLexer)
 *  -  void      pProtoJSLexer->EXTENSIONS(pProtoJSLexer)
 *  -  void      pProtoJSLexer->RESERVE(pProtoJSLexer)
 *  -  void      pProtoJSLexer->TO(pProtoJSLexer)
 *  -  void      pProtoJSLexer->ENUM(pProtoJSLexer)
 *  -  void      pProtoJSLexer->FLAGS8(pProtoJSLexer)
 *  -  void      pProtoJSLexer->FLAGS16(pProtoJSLexer)
 *  -  void      pProtoJSLexer->FLAGS32(pProtoJSLexer)
 *  -  void      pProtoJSLexer->FLAGS64(pProtoJSLexer)
 *  -  void      pProtoJSLexer->REQUIRED(pProtoJSLexer)
 *  -  void      pProtoJSLexer->ProtoJSOPTIONAL(pProtoJSLexer)
 *  -  void      pProtoJSLexer->REPEATED(pProtoJSLexer)
 *  -  void      pProtoJSLexer->DEFAULT(pProtoJSLexer)
 *  -  void      pProtoJSLexer->EQUALS(pProtoJSLexer)
 *  -  void      pProtoJSLexer->BLOCK_OPEN(pProtoJSLexer)
 *  -  void      pProtoJSLexer->BLOCK_CLOSE(pProtoJSLexer)
 *  -  void      pProtoJSLexer->ITEM_TERMINATOR(pProtoJSLexer)
 *  -  void      pProtoJSLexer->UINT8(pProtoJSLexer)
 *  -  void      pProtoJSLexer->INT8(pProtoJSLexer)
 *  -  void      pProtoJSLexer->SINT8(pProtoJSLexer)
 *  -  void      pProtoJSLexer->FIXED8(pProtoJSLexer)
 *  -  void      pProtoJSLexer->SFIXED8(pProtoJSLexer)
 *  -  void      pProtoJSLexer->UINT16(pProtoJSLexer)
 *  -  void      pProtoJSLexer->INT16(pProtoJSLexer)
 *  -  void      pProtoJSLexer->SINT16(pProtoJSLexer)
 *  -  void      pProtoJSLexer->FIXED16(pProtoJSLexer)
 *  -  void      pProtoJSLexer->SFIXED16(pProtoJSLexer)
 *  -  void      pProtoJSLexer->UINT32(pProtoJSLexer)
 *  -  void      pProtoJSLexer->INT32(pProtoJSLexer)
 *  -  void      pProtoJSLexer->SINT32(pProtoJSLexer)
 *  -  void      pProtoJSLexer->FIXED32(pProtoJSLexer)
 *  -  void      pProtoJSLexer->SFIXED32(pProtoJSLexer)
 *  -  void      pProtoJSLexer->UINT64(pProtoJSLexer)
 *  -  void      pProtoJSLexer->INT64(pProtoJSLexer)
 *  -  void      pProtoJSLexer->SINT64(pProtoJSLexer)
 *  -  void      pProtoJSLexer->FIXED64(pProtoJSLexer)
 *  -  void      pProtoJSLexer->SFIXED64(pProtoJSLexer)
 *  -  void      pProtoJSLexer->FLOAT(pProtoJSLexer)
 *  -  void      pProtoJSLexer->DOUBLE(pProtoJSLexer)
 *  -  void      pProtoJSLexer->BOOL(pProtoJSLexer)
 *  -  void      pProtoJSLexer->BYTES(pProtoJSLexer)
 *  -  void      pProtoJSLexer->STRING(pProtoJSLexer)
 *  -  void      pProtoJSLexer->UUID(pProtoJSLexer)
 *  -  void      pProtoJSLexer->SHA256(pProtoJSLexer)
 *  -  void      pProtoJSLexer->ANGLE(pProtoJSLexer)
 *  -  void      pProtoJSLexer->TIME(pProtoJSLexer)
 *  -  void      pProtoJSLexer->DURATION(pProtoJSLexer)
 *  -  void      pProtoJSLexer->NORMAL(pProtoJSLexer)
 *  -  void      pProtoJSLexer->VECTOR2F(pProtoJSLexer)
 *  -  void      pProtoJSLexer->VECTOR2D(pProtoJSLexer)
 *  -  void      pProtoJSLexer->VECTOR3F(pProtoJSLexer)
 *  -  void      pProtoJSLexer->VECTOR3D(pProtoJSLexer)
 *  -  void      pProtoJSLexer->VECTOR4F(pProtoJSLexer)
 *  -  void      pProtoJSLexer->VECTOR4D(pProtoJSLexer)
 *  -  void      pProtoJSLexer->UNITQUATERNION(pProtoJSLexer)
 *  -  void      pProtoJSLexer->QUATERNION(pProtoJSLexer)
 *  -  void      pProtoJSLexer->BOUNDINGSPHERE3F(pProtoJSLexer)
 *  -  void      pProtoJSLexer->BOUNDINGSPHERE3D(pProtoJSLexer)
 *  -  void      pProtoJSLexer->BOUNDINGBOX3F3F(pProtoJSLexer)
 *  -  void      pProtoJSLexer->BOUNDINGBOX3D3F(pProtoJSLexer)
 *  -  void      pProtoJSLexer->SQBRACKET_OPEN(pProtoJSLexer)
 *  -  void      pProtoJSLexer->SQBRACKET_CLOSE(pProtoJSLexer)
 *  -  void      pProtoJSLexer->STRING_LITERAL(pProtoJSLexer)
 *  -  void      pProtoJSLexer->STRING_GUTS(pProtoJSLexer)
 *  -  void      pProtoJSLexer->OPTION_LITERAL(pProtoJSLexer)
 *  -  void      pProtoJSLexer->BOOL_LITERAL(pProtoJSLexer)
 *  -  void      pProtoJSLexer->HEX_LITERAL(pProtoJSLexer)
 *  -  void      pProtoJSLexer->DECIMAL_LITERAL(pProtoJSLexer)
 *  -  void      pProtoJSLexer->OCTAL_LITERAL(pProtoJSLexer)
 *  -  void      pProtoJSLexer->HexDigit(pProtoJSLexer)
 *  -  void      pProtoJSLexer->FLOATING_POINT_LITERAL(pProtoJSLexer)
 *  -  void      pProtoJSLexer->Exponent(pProtoJSLexer)
 *  -  void      pProtoJSLexer->EscapeSequence(pProtoJSLexer)
 *  -  void      pProtoJSLexer->OctalEscape(pProtoJSLexer)
 *  -  void      pProtoJSLexer->UnicodeEscape(pProtoJSLexer)
 *  -  void      pProtoJSLexer->IDENTIFIER(pProtoJSLexer)
 *  -  void      pProtoJSLexer->QUALIFIEDIDENTIFIER(pProtoJSLexer)
 *  -  void      pProtoJSLexer->IDENTIFIERCOLON(pProtoJSLexer)
 *  -  void      pProtoJSLexer->COMMENT(pProtoJSLexer)
 *  -  void      pProtoJSLexer->WS(pProtoJSLexer)
 *  -  void      pProtoJSLexer->PAREN_OPEN(pProtoJSLexer)
 *  -  void      pProtoJSLexer->PAREN_CLOSE(pProtoJSLexer)
 *  -  void      pProtoJSLexer->QUOTE(pProtoJSLexer)
 *  -  void      pProtoJSLexer->COMMA(pProtoJSLexer)
 *  -  void      pProtoJSLexer->COLON(pProtoJSLexer)
 *  -  void      pProtoJSLexer->Tokens(pProtoJSLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_ProtoJSLexer_H
#define _ProtoJSLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */
 
#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct ProtoJSLexer_Ctx_struct ProtoJSLexer, * pProtoJSLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule 
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for ProtoJSLexer
 */
struct ProtoJSLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;


     void (*mPACKAGELITERAL)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mIMPORTLITERAL)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mDOT)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mSERVICE)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mRPC)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mRETURNS)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mMESSAGE)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mEXTEND)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mEXTENSIONS)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mRESERVE)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mTO)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mENUM)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mFLAGS8)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mFLAGS16)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mFLAGS32)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mFLAGS64)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mREQUIRED)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mProtoJSOPTIONAL)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mREPEATED)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mDEFAULT)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mEQUALS)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mBLOCK_OPEN)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mBLOCK_CLOSE)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mITEM_TERMINATOR)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mUINT8)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mINT8)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mSINT8)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mFIXED8)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mSFIXED8)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mUINT16)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mINT16)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mSINT16)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mFIXED16)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mSFIXED16)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mUINT32)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mINT32)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mSINT32)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mFIXED32)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mSFIXED32)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mUINT64)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mINT64)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mSINT64)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mFIXED64)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mSFIXED64)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mFLOAT)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mDOUBLE)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mBOOL)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mBYTES)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mSTRING)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mUUID)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mSHA256)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mANGLE)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mTIME)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mDURATION)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mNORMAL)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mVECTOR2F)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mVECTOR2D)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mVECTOR3F)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mVECTOR3D)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mVECTOR4F)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mVECTOR4D)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mUNITQUATERNION)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mQUATERNION)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mBOUNDINGSPHERE3F)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mBOUNDINGSPHERE3D)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mBOUNDINGBOX3F3F)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mBOUNDINGBOX3D3F)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mSQBRACKET_OPEN)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mSQBRACKET_CLOSE)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mSTRING_LITERAL)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mSTRING_GUTS)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mOPTION_LITERAL)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mBOOL_LITERAL)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mHEX_LITERAL)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mDECIMAL_LITERAL)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mOCTAL_LITERAL)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mHexDigit)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mFLOATING_POINT_LITERAL)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mExponent)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mEscapeSequence)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mOctalEscape)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mUnicodeEscape)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mIDENTIFIER)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mQUALIFIEDIDENTIFIER)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mIDENTIFIERCOLON)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mCOMMENT)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mWS)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mPAREN_OPEN)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mPAREN_CLOSE)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mQUOTE)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mCOMMA)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mCOLON)	(struct ProtoJSLexer_Ctx_struct * ctx);
     void (*mTokens)	(struct ProtoJSLexer_Ctx_struct * ctx);    const char * (*getGrammarFileName)();
    void	    (*free)   (struct ProtoJSLexer_Ctx_struct * ctx);
        
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pProtoJSLexer ProtoJSLexerNew         (pANTLR3_INPUT_STREAM instream);
ANTLR3_API pProtoJSLexer ProtoJSLexerNewSSD      (pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the lexer will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif 
#define SINT16      68
#define SHA256      76
#define FLAGS64      85
#define VECTOR3F      52
#define FLAGS8      82
#define VECTOR3D      53
#define INT8      63
#define EQUALS      25
#define FIXED64      44
#define EOF      -1
#define QUOTE      95
#define STRING_LITERAL      5
#define FLOATING_POINT_LITERAL      80
#define VECTOR2D      51
#define VECTOR2F      50
#define UINT16      71
#define FIXED8      65
#define DOUBLE      35
#define SINT32      38
#define COMMENT      93
#define IDENTIFIERCOLON      92
#define INT16      67
#define BLOCK_OPEN      12
#define QUATERNION      57
#define QUALIFIEDIDENTIFIER      8
#define PAREN_CLOSE      16
#define ITEM_TERMINATOR      7
#define BOOL      46
#define REPEATED      28
#define BOOL_LITERAL      81
#define UINT64      41
#define DURATION      74
#define INT32      37
#define SINT8      64
#define FLAGS32      84
#define BLOCK_CLOSE      13
#define WS      94
#define SERVICE      11
#define FIXED16      69
#define SFIXED16      70
#define PACKAGELITERAL      6
#define ProtoJSOPTIONAL      26
#define BYTES      48
#define RPC      14
#define IMPORTLITERAL      10
#define DECIMAL_LITERAL      78
#define EscapeSequence      87
#define SQBRACKET_CLOSE      31
#define BOUNDINGBOX3F3F      60
#define UINT8      62
#define UUID      75
#define STRING_GUTS      86
#define Exponent      89
#define FLOAT      34
#define HexDigit      88
#define BOUNDINGBOX3D3F      61
#define TIME      73
#define EXTEND      20
#define SINT64      43
#define EXTENSIONS      21
#define COMMA      18
#define IDENTIFIER      9
#define FIXED32      39
#define SQBRACKET_OPEN      30
#define SFIXED32      40
#define MESSAGE      19
#define HEX_LITERAL      77
#define FLAGS16      83
#define DOT      29
#define NORMAL      49
#define RETURNS      17
#define ANGLE      72
#define INT64      42
#define TO      22
#define DEFAULT      33
#define BOUNDINGSPHERE3D      59
#define OPTION_LITERAL      32
#define OCTAL_LITERAL      79
#define RESERVE      23
#define BOUNDINGSPHERE3F      58
#define REQUIRED      27
#define COLON      96
#define UNITQUATERNION      56
#define ENUM      24
#define SFIXED64      45
#define UnicodeEscape      91
#define VECTOR4D      55
#define UINT32      36
#define VECTOR4F      54
#define PAREN_OPEN      15
#define PROTO      4
#define OctalEscape      90
#define SFIXED8      66
#define STRING      47
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for ProtoJSLexer
 * =============================================================================
 */
/** \} */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
